### ISSUE TITLE
could not find function "deconv_simple"

### ISSUE THREAD

**Issue by zhuy16** [meichendong/SCDC#14]
This happened when running the SCDC.rmd file, there seems no function ""deconv_simple". ? Thanks!

res = deconv_simple(count.filter.norm, basis.norm)
res$prop.est.mvw
​
Error in deconv_simple(count.filter.norm, basis.norm): could not find function "deconv_simple"
Traceback:

**Comment by meichendong** [comment]
Hi @zhuy16, thanks for reporting this bug! I've updated it and you should be able to find it now.

**Comment by meichendong** [comment]
Hi @zhuy16, thanks for reporting this bug! I've updated it and you should be able to find it now.

**Comment by meichendong** [comment]
Hi @zhuy16, thanks for reporting this bug! I've updated it and you should be able to find it now.

**Comment by meichendong** [comment]
Hi @zhuy16, thanks for reporting this bug! I've updated it and you should be able to find it now.

**Comment by meichendong** [comment]
Hi @zhuy16, thanks for reporting this bug! I've updated it and you should be able to find it now.

**Comment by meichendong** [comment]
Hi @zhuy16, thanks for reporting this bug! I've updated it and you should be able to find it now.
