### ISSUE TITLE
getCPM0  creates issue with only one bulk sample

### ISSUE THREAD

**Issue by PelzKo** [meichendong/SCDC#27]
When running SCDC (specifically the function SCDC_prop) with just one bulk sample, it fails at this line: https://github.com/meichendong/SCDC/blob/master/R/Deconvolution.R#L646 as yhat does not contain any columnnames.
This is due to this line: https://github.com/meichendong/SCDC/blob/master/R/Deconvolution.R#L584 where, if just one bulk sample is supplies, it is treated as a vector and the column name is lost.

Is this intentional? Can SCDC just be used with more than one sample or could a simple `,drop=FALSE` solve the problem?

**Comment by meichendong** [comment]
Hi @PelzKo , thanks for reporting the issue. This was not intentional. Your suggestion should work and I updated the function.
