### ISSUE TITLE
SCDC_qc() requires cbPalette

### ISSUE THREAD

**Issue by t-carroll** [meichendong/SCDC#3]
When running SCDC_qc(), the function failed at the very end of the iteration process and threw the following error:

Error in seq.default(min(x, na.rm = T), max(x, na.rm = T), length.out = n +  : 
  object 'cbPalette' not found

From looking through the code it looks like this function expects the cbPalette to be in the users environment to draw the heatmap, and I did not have this installed. I was able to resolve this error by loading cbPalette manually with the following commands before running SCDC_qc():
`install_github("wgaul/wgutil")
library(wgutil)
data(cbPalette)`

For future users who may encounter this error, would it be possible to include cbPalette as a part of the installation process?

**Comment by meichendong** [comment]
Hi,
Thanks for using SCDC! We have added the default values for the cbPalette in the function. It should work now.
