### ISSUE TITLE
The argument 'prop_mat' to the function 'generateBulk_norep' does not seem to work

### ISSUE THREAD

**Issue by sjebmeier** [meichendong/SCDC#4]
Dear Dr Dong,

Many thanks for writing this package and accompanying vignette - in general I have found it very easy to understand and use.

I have had one problem with manually inputting cell-type proportions for pseudo bulk samples with the function 'generateBulk_norep'. Although the function has accepted the matrix I submitted to the argument 'prop_mat', the resulting pseudobulk object does not have the cell-type proportions I specified.

Any help would be much appreciated.

**Comment by meichendong** [comment]
Hi, 
The most recent version should have this issue fixed.

Thanks,
Meichen
