### ISSUE TITLE
SCDC_ENSEMBLE problem

### ISSUE THREAD

**Issue by qq2006tom-cmd** [meichendong/SCDC#7]
Hi

I am trying to use your tool to analyze part of my data. When I did SCDC_ENSEMBLE, I got an error: Error in lsfit(x, y, intercept = FALSE) : only 0 cases, but 1 variable. I am wondering if you could give me some suggestions to fix the problem. 

Thank you.

**Comment by sariya** [comment]
Hi @qq2006tom-cmd @meichendong 

I also get the same error. My input list contains only one single-cell object (multiple subjects within it)

Were you able to resolve this?

**Comment by meichendong** [comment]
Hi @sariya ,
Thanks for using our package! I wonder if you could please provide more details? Did you check whether the gene names match for sc and bulk data? for one-subject case, please use SCDC_qc_ONE(), SCDC_prop_ONE() functions. 
Please feel free to contact me via email meichen@live.unc.edu
